# Generated by Django 4.2.7 on 2023-12-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiauto', '0002_examplemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdowncontent',
            name='content',
        ),
    ]
