# Generated by Django 4.2.7 on 2023-12-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauto', '0003_remove_markdowncontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
