# Generated by Django 4.2.7 on 2023-12-09 03:07

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apiauto', '0004_markdowncontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdowncontent',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
